### ISSUE TITLE
AdapterRemoval defaults to --qualitybase 64

### ISSUE THREAD

**Issue by ivelsko** [maxibor/madman#10]
I got madman to run successfully, but it had an issue with my input files. I ran `run maxibor/madman -profile test,shh --reads ‘/projects1/microbiome_calculus/abpCapture/04-analysis/AB_assembly/set1/input/ancient/ECO*.AB1.1_S0_L005_R{1,
2}_001.fastq.gz’ --metaspades` and the input files are capture data from our HiSeq4000, which should be phred33 by default. It gave this error: 
```
Execution cancelled -- Finishing pending tasks before exit
-[nf-core/madman] Pipeline completed with errors-
Error executing process > 'PRE_ASSEMBLY:adapterremoval (ECO002.B0101)'

Caused by:
  Process `PRE_ASSEMBLY:adapterremoval (ECO002.B0101)` terminated with an error exit status (1)

Command executed:

  AdapterRemoval --basename ECO002.B0101                            --file1 ECO002.B0101.AB1.1_S0_L005_R1_001.fastq.gz                            --file2 ECO002.B0101.AB1.1_S0_L005_R2_001.fastq.gz                            --trimns                            --trimqualit
ies                            --minquality 20                            --minlength 30                            --output1 ECO002.B0101.pair1.trimmed.fastq                            --output2 ECO002.B0101.pair2.trimmed.fastq                            --threads 2
                       --qualitybase 64                            --adapter-list adapter_list.txt                            --settings ECO002.B0101.settings

Command exit status:
  1

Command output:
  (empty)

Command error:
  Read 1 adapters / adapter pairs from 'adapter_list.txt'...
  Trimming paired end reads ...
  Opening FASTQ file 'ECO002.B0101.AB1.1_S0_L005_R1_001.fastq.gz', line numbers start at 1
  Error reading FASTQ record at line 1; aborting:
      Phred+64 encoded quality score is less than 0 (ASCII < ';'); Are these FASTQ
      reads actually in Phred+33 format? If so, use the command-line option
      "--qualitybase 33"

      See README for more information.
  Aborting thread due to error.
  ERROR: AdapterRemoval did not run to completion;
         do NOT make use of resulting trimmed reads!

Work dir:
  /projects1/microbiome_calculus/abpCapture/04-analysis/AB_assembly/set1/madman/test_ancient/work/f6/94e40a22b687a696075cc3ceca75cd

Tip: you can try to figure out what's wrong by changing to the process work dir and showing the script file named `.command.sh`
```

Where it assumed Phred64. 

I checked the problem file `/projects1/microbiome_calculus/abpCapture/04-analysis/AB_assembly/set1/input/ancient/ECO002.B0101.AB1.1_S0_L005_R1_001.fastq.gz` and the first read starts with an ‘N’, which I think caused this issue. I set the flag `--phred 33` and then it ran fine.

Is there anything you can do to make it not use `--qualitybase 64` in a case like this, or would you just recommend always setting the `--phred` flag?

**Comment by maxibor** [comment]
Hi @ivelsko ,
The `test` profile is meant to be used to test the changes of the pipeline, with [test-data](https://github.com/maxibor/madman/tree/master/test/data), which are phred 64 encoded, hence this flag.
When not using the `test` profile, the default is `--qualitybase` is 33 (you don't need to set the flag.)

In general, the `test` profile is not meant to be used for you own data ;)
